### ISSUE TITLE
qnanopainter worked with "Ubuntu SDK" based on Qt 5.2.1, now doesn't compile

### ISSUE THREAD

**Issue by NielsMayer** [QUItCoding/qnanopainter#27]
With the application of a trivial QML patch, QNanoPainter used to compile and work with "Ubuntu SDK" ( https://packages.ubuntu.com/search?keywords=ubuntu-sdk-libs ) which is a convenient way to get Qt5 and a properly working QtMultimedia on Ubuntu (unlike latest Qt 5.6/5.9/5.10 releases).

With latest changes to qnanopainter (TBD -- I'm trying to identify which changes did this compared to my locally working sourcecode).

First error: 
```
qnanopainter/examples/qnanopainter_vs_qpainter_demo/src/demoqnanoitempainter.cpp
g++ -c -m64 -pipe -O2 -std=c++0x -Wall -W -D_REENTRANT -fPIE -DQNANO_QT_GL_INCLUDE -DQNANO_ENABLE_GLES3 -DQT_NO_DEBUG_OUTPUT -DQT_NO_INFO_OUTPUT -DQT_NO_DEBUG -DQT_QUICK_LIB -DQT_QML_LIB -DQT_NETWORK_LIB -DQT_GUI_LIB -DQT_CORE_LIB -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I../../../copy-of-qnanopainter/examples/qnanopainter_vs_qpainter_demo -I../../../copy-of-qnanopainter/libqnanopainter -I/usr/include/qt5 -I/usr/include/qt5/QtQuick -I/usr/include/qt5/QtQml -I/usr/include/qt5/QtNetwork -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtCore -I. -I. -o qnanopainter.o ../../../copy-of-qnanopainter/libqnanopainter/qnanopainter.cpp
../../../copy-of-qnanopainter/libqnanopainter/qnanopainter.cpp: In constructor ‘QNanoPainter::QNanoPainter()’:
../../../copy-of-qnanopainter/libqnanopainter/qnanopainter.cpp:145:20: error: ‘openGLModuleType’ is not a member of ‘QOpenGLContext’
     bool isGLES = (QOpenGLContext::openGLModuleType() == QOpenGLContext::LibGLES);
                    ^
../../../copy-of-qnanopainter/libqnanopainter/qnanopainter.cpp:145:58: error: ‘LibGLES’ is not a member of ‘QOpenGLContext’
     bool isGLES = (QOpenGLContext::openGLModuleType() == QOpenGLContext::LibGLES);
                                                          ^
```
Another: 

```
g++ -c -m64 -pipe -O2 -std=c++0x -Wall -W -D_REENTRANT -fPIE -DQNANO_QT_GL_INCLUDE -DQNANO_ENABLE_GLES3 -DQT_NO_DEBUG_OUTPUT -DQT_NO_INFO_OUTPUT -DQT_NO_DEBUG -DQT_QUICK_LIB -DQT_QML_LIB -DQT_NETWORK_LIB -DQT_GUI_LIB -DQT_CORE_LIB -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I../../../copy-of-qnanopainter/examples/qnanopainter_vs_qpainter_demo -I../../../copy-of-qnanopainter/libqnanopainter -I/usr/include/qt5 -I/usr/include/qt5/QtQuick -I/usr/include/qt5/QtQml -I/usr/include/qt5/QtNetwork -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtCore -I. -I. -o qnanowindow.o ../../../copy-of-qnanopainter/libqnanopainter/qnanowindow.cpp
In file included from ../../../copy-of-qnanopainter/libqnanopainter/qnanowindow.cpp:22:0:
../../../copy-of-qnanopainter/libqnanopainter/qnanowindow.h:25:25: fatal error: QOpenGLWindow: No such file or directory
 #include <QOpenGLWindow>
                         ^
```

Just for reference, when running with Ubuntu SDK, (and envar  QSG_INFO set to emit debug info), the output looks like: 
```
Starting /home/npm/src/build-qnanopainter-Ubuntu_SDK_5_2_1_GCC_x86_64bit_in_usr_bin-Release/examples/gallery/gallery...
QSG: threaded render loop 
QSG: texture atlas dimensions: 512 x 1024 
GL_VENDOR:      X.Org 
GL_RENDERER:    Gallium 0.4 on AMD CAPE VERDE (DRM 2.48.0, LLVM 3.6.0) 
GL_VERSION:     3.0 Mesa 11.0.4 
GL_EXTENSIONS:
    GL_ARB_multisample
```

Here is the trivial QML patch to enable gallery and qnanopainter-vs examples to work with Ubuntu SDK. It is trivial in that all it does is roll back Qt versions of various QML imports to whatever was available with Qt 5.2.1. 

[qnanopainter-make-qml-compatible-with-ubuntu-sdk.patch.gz](https://github.com/QUItCoding/qnanopainter/files/1980875/qnanopainter-make-qml-compatible-with-ubuntu-sdk.patch.gz)

**Comment by NielsMayer** [comment]
I've uninstalled "Ubuntu SDK" so this issue no longer matters to me and I have no way of testing its resolution. Incidentally "Ubuntu SDK" had installed some other libs/etc as dependencies that were causing other bugs in other systems, and I was able to get Qt 5.6.3's Qt MultiMedia to work for my purposes, thus no need for "Ubuntu SDK" anymore. Sorry for the disturbance. :-)
