### ISSUE TITLE
Compilation errors with Qt6.0.0

### ISSUE THREAD

**Issue by NielsMayer** [QUItCoding/qnanopainter#56]
Qt 6.0.0 alpha has been released ( https://www.qt.io/blog/qt-6.0-alpha-released ).

In order to get qnanopainter compilation going at all with Qt6, I first had to modify libqnanopainter/include.pri:

```
diff --git a/libqnanopainter/include.pri b/libqnanopainter/include.pri
index 079eb6e..6c8ddae 100644
--- a/libqnanopainter/include.pri
+++ b/libqnanopainter/include.pri
@@ -5,6 +5,13 @@ INCLUDEPATH += $$PWD/
 # Use c++11 features
 CONFIG += c++11

+##NPM: for Qt6, need opengl module
+## https://doc-snapshots.qt.io/qt6-dev/qtopengl-index.html
+equals(QT_MAJOR_VERSION, 6) {
+   QT += opengl
+}
+
+
 # Enable this to get drawing debug information
 #DEFINES += QNANO_DEBUG
```

With this change in place, I was able to get compilation going, but with numerous errors -- see attached file.
There are lots of deprecation warnings, but I'm not going to concentrate on that here.

Some examples of such errors;

- error:` ‘geometryChanged’ is not a member of ‘QQuickItem’`

- error: `‘class QQuickWindow’ has no member named ‘resetOpenGLState’; did you mean ‘setWindowState’? `

-  fatal error:` QOpenGLWidget: No such file or directory`

Others are more trivial: 

- error: `‘qrand’ was not declared in this scope`

**Comment by NielsMayer** [comment]
Here are the compilation errors: https://gist.github.com/NielsMayer/6253051f2df10ff90f279aa84e3c78a4

**Comment by NielsMayer** [comment]
Note the following https://doc-snapshots.qt.io/qt6-dev/qtgui-index.html#opengl-and-opengl-es-integration
```
OpenGL and OpenGL ES Integration
QWindow supports rendering using OpenGL and OpenGL ES, depending on what the platform supports. OpenGL rendering is enabled by setting the QWindow's surface type to QSurface::OpenGLSurface, choosing the format attributes with QSurfaceFormat, and then creating a QOpenGLContext to manage the native OpenGL context. In addition, Qt has QOpenGLPaintDevice, which enables the use of OpenGL accelerated QPainter rendering, as well as convenience classes that simplify the writing of OpenGL code and hides the complexities of extension handling and the differences between OpenGL ES 2 and desktop OpenGL. The convenience classes include QOpenGLFunctions that lets an application use all the OpenGL ES 2 functions on desktop OpenGL without having to manually resolve the OpenGL function pointers, thus allowing cross-platform development of applications targeting mobile or embedded devices, and some classes that wrap native OpenGL functionality in a simpler Qt API:

QOpenGLBuffer
QOpenGLFramebufferObject
QOpenGLShaderProgram
QOpenGLTexture
QOpenGLDebugLogger
QOpenGLTimerQuery
QOpenGLVertexArrayObject
Finally, in order to provide better support for the newer versions (3.0 and higher) of OpenGL, a versioned function wrapper mechanism is also available: The QOpenGLFunction_N_N family of classes expose all the functions in a given OpenGL version and profile, allowing easy development of desktop applications relying on modern, desktop-only OpenGL features.
```

**Comment by NielsMayer** [comment]
I managed to significantly reduce the compilation errors for QNanoQuickItem based interfaces by adding
`#include <QtOpenGL>          //NPM: for Qt>=6.0.0 opengl compatibility module needed (QT += opengl)`
to libqnanopainter/qnanoquickitempainter.h

and in libqnanopainter/qnanoquickitem.h changed QNANO_QUICKITEM_UPDATE:
```
#if QT_VERSION >= 0x060000  // NPM: support Qt 6.00 and later -- TODO -- this compiles but is it correct?
#  define QNANO_QUICKITEM_UPDATE QMetaObject::invokeMethod(this, "update");
#elif QT_VERSION >= 0x051000  // Qt 5.10 and later
#  define QNANO_QUICKITEM_UPDATE QMetaObject::invokeMethod(this, &QNanoQuickItem::update);
#else
#  define QNANO_QUICKITEM_UPDATE QMetaObject::invokeMethod(this, "update");
#endif
```
After these changes, the only errors I see in a QQuickItem based qnanopainter  code are compile error like this:

```
 error: ‘geometryChanged’ is not a member of ‘QQuickItem’
     QQuickItem::geometryChanged(newGeometry, oldGeometry);
```
I am currently investigating why the above error happens in Qt6 and will update when I get it compiled/running.

After I manage to get QNanoQuickItem working, I'll look into the errors in the "Widget" QNanoPainter code, using examples from
https://doc-snapshots.qt.io/qt6-dev/examples-widgets-opengl.html to see how things changed for Qt6.

I note that the opengl module documentation mentions 
> ""Warning: This module should not be used anymore for new code. Please use the corresponding OpenGL classes in Qt GUI."
so the changes I'm attempting aren't necessarily optimal going forward once Qt5 becomes obsolete.

**Comment by NielsMayer** [comment]
Turns out the geometryChanged() problem is a simple name change, solved via:

```
#if (QT_VERSION >= 0x060000)
    QQuickItem::geometryChange(newGeometry, oldGeometry);
#else
    QQuickItem::geometryChanged(newGeometry, oldGeometry);
#endif
```

**Comment by NielsMayer** [comment]
I finally got my app to compile with no errors on Qt6.0.0 alpha.

The error:
 - ‘class QQuickWindow’ has no member named ‘resetOpenGLState’; did you mean ‘setWindowState’

is fixed by some small changes to libqnanopainter/qnanoquickitempainter.cpp:

```
#if (QT_VERSION >= 0x060000)         //NPM: changes for Qt6
#include <QQuickOpenGLUtils>         //NPM: QQuickOpenGLUtils::resetOpenGLState()
#endif /* (QT_VERSION >= 0x060000) */
```

and wih the new definitions in place, the resetOpenGLState() call becomes: 

```
    // Reset the GL state for Qt side
    if (m_window) {
#if (QT_VERSION >= 0x060000)         //NPM: changes for Qt6
        QQuickOpenGLUtils::resetOpenGLState();
#else
        m_window->resetOpenGLState();
#endif /* (QT_VERSION >= 0x060000) */
    }
```

Once I get it running, I'll try to put together some patches or a pull request to at least fix the QNanoQuickItem based interfaces.

**Comment by NielsMayer** [comment]
I was able to get all but the hellowidget example running on Qt6. 

I conditionalized the build via qnanopainter.pro modification to not add hellowidget example if Qt6 detected. In Qt6, 
`QOpenGLWidget` is not defined. See https://doc-snapshots.qt.io/qt6-dev/qtopengl-module.html and https://doc-snapshots.qt.io/qt6-dev/qtgui-index.html#opengl-and-opengl-es-integration for details ...

Due to installation errors (turns out I need to run on Ubuntu 20.04 not 18.04.5) I was only able to get "egfls" Qt platform working.

Output for running qnanopainter_vs_qpainter_demo (looks fine) under eglfs looks like this:

```
22:04:28: Starting /usr/local/src/build-qnanopainter-Desktop_Qt_6_0_0_GCC_64bit-Release/examples/qnanopainter_vs_qpainter_demo/qnanopainter_vs_qpainter_demo ...
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-npm'
qt.scenegraph.general: Using QRhi with backend OpenGL
  graphics API debug/validation layers: 0
  QRhi profiling and debug markers: 0
qt.scenegraph.general: threaded render loop
qt.scenegraph.general: Using sg animation driver
qt.scenegraph.general: Animation Driver: using vsync: 16.67 ms
libpng warning: iCCP: known incorrect sRGB profile
qt.scenegraph.general: Using sg animation driver
qt.scenegraph.general: Animation Driver: using vsync: 16.67 ms
qt.rhi.general: Created OpenGL context QSurfaceFormat(version 4.6, options QFlags<QSurfaceFormat::FormatOption>(DeprecatedFunctions), depthBufferSize 24, redBufferSize 8, greenBufferSize 8, blueBufferSize 8, alphaBufferSize 0, stencilBufferSize 8, samples 0, swapBehavior QSurfaceFormat::DefaultSwapBehavior, swapInterval 1, colorSpace QColorSpace(), profile  QSurfaceFormat::CompatibilityProfile)
qt.rhi.general: OpenGL VENDOR: X.Org RENDERER: Radeon RX Vega (VEGA10, DRM 3.35.0, 5.4.0-48-generic, LLVM 10.0.0) VERSION: 4.6 (Compatibility Profile) Mesa 20.0.8
qt.scenegraph.general: MSAA sample count for the swapchain is 1. Alpha channel requested = no.
qt.scenegraph.general: rhi texture atlas dimensions: 8192x4096
```

@QUItCoding : I will submit a PR with the changes I did for Qt6 compilation and running.

I was planning on filing an issue "will qnanopainter work with Qt6" but I have answered my own question. I will probably need to wait till Qt6.1 for my own projects because they're dependent on qtmultimedia which is not supported in 6.0 per https://www.qt.io/blog/qt-6.0-feature-freeze-milestone-reached but at least I now know what effect Qt6 will have on the future of my projects... None!

**Comment by NielsMayer** [comment]
Looks like QOpenGLWidget is supported after all, per https://doc-snapshots.qt.io/qt6-dev/sourcebreaks.html#changes-to-qt-ope
: 
> QOpenGLWidget has been moved to its own openglwidgets module. Applications relying on QOpenGLWidget should add QT += openglwidgets to their project file.

So I will continue updating my PR repo with this change and then submit the PR when all is well.

**Comment by QUItCoding** [comment]
..couldn't wait, had to test already 😄 Windows needs additional QOpenGLFunctions change, I can do that separetely. Also for Quick examples to work, RHI backend needs to be set to use OpenGL (default on windows is d3d11). With those changes I was able to run all examples on windows + latest Qt6 dev, so merged the patch.
